### ISSUE TITLE
Use Case 3: interaction diagrams

### ISSUE THREAD

**Issue by DavidZ08** [DavidZ08/SOEN342-project#39]
Revise all of the interaction diagrams for them to be accurate with the final implementation. **TO BE DONE AFTER IMPLEMENTATION**.

**Comment by NourHadieHassoun** [comment]
Interaction Diagram 1- Collaboration Diagram : <img width="732" alt="Interaction diagram 2-Collaboration Diagram" src="https://github.com/DavidZ08/SOEN342-project/assets/102493688/6cd58ed7-2eb2-49b0-abfc-0fac144160ee">

Interaction Diagram 2- Sequence Diagram :
![Interaction diagram 2-Sequence Diagram](https://github.com/DavidZ08/SOEN342-project/assets/102493688/a54808df-2131-4b4d-9296-e04761cba158)
