### ISSUE TITLE
Use Case 3: Final identification of system operations and operation contracts

### ISSUE THREAD

**Issue by DavidZ08** [DavidZ08/SOEN342-project#40]
Revise all of the system operations and operations contracts for them to be accurate with the final implementation. **TO BE DONE AFTER IMPLEMENTATION**.

**Comment by Dopyo** [comment]
![image](https://github.com/DavidZ08/SOEN342-project/assets/79109566/f73db16f-9b61-46a9-9e81-9df1df0835f6)
![image](https://github.com/DavidZ08/SOEN342-project/assets/79109566/83f0e97d-881d-4c42-b612-ee43292c200a)
![image](https://github.com/DavidZ08/SOEN342-project/assets/79109566/2cbadacf-431b-45f5-a632-6b831df360c6)
![image](https://github.com/DavidZ08/SOEN342-project/assets/79109566/aa1795f5-b9bf-4fc1-a18e-e9b6f4e9c906)
